// <auto-generated />
using System;
using System.Collections.Generic;
using Applications.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Applications.WebApi.Migrations.Postgres
{
    [DbContext(typeof(CreditApplicationDbContextPostgres))]
    [Migration("20260822163450_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Applications.Application.Domain.Application.CreditApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CreditPeriodInMonths")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CustomerPersonalData", "Applications.Application.Domain.Application.CreditApplication.CustomerPersonalData#CustomerPersonalData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DocumentId")
                                .IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired();

                            b1.Property<string>("LastName")
                                .IsRequired();

                            b1
                                .ToJson("CustomerPersonalData")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Declaration", "Applications.Application.Domain.Application.CreditApplication.Declaration#Declaration", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("AverageNetMonthlyIncome");

                            b1
                                .ToJson("Declaration")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "States", "Applications.Application.Domain.Application.CreditApplication.States#ApplicationState", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Date");

                            b1.Property<int>("Decision");

                            b1.Property<int>("Level");

                            b1
                                .ToJson("States")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.ToTable("CreditApplication", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
