// <auto-generated />
using Applications.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Applications.WebApi.Migrations.Postgres
{
    [DbContext(typeof(CreditApplicationDbContextPostgres))]
    partial class CreditApplicationDbContextPostgresModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Applications.Application.Domain.Application.CreditApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CreditPeriodInMonths")
                        .HasColumnType("integer");

                    b.Property<string>("States")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CreditApplication", (string)null);
                });

            modelBuilder.Entity("Applications.Application.Domain.Application.CreditApplication", b =>
                {
                    b.OwnsOne("Applications.Application.Domain.Application.CustomerPersonalData", "CustomerPersonalData", b1 =>
                        {
                            b1.Property<string>("CreditApplicationId");

                            b1.Property<string>("DocumentId")
                                .IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired();

                            b1.Property<string>("LastName")
                                .IsRequired();

                            b1.HasKey("CreditApplicationId");

                            b1.ToTable("CreditApplication");

                            b1.ToJson("CustomerPersonalData");

                            b1.WithOwner()
                                .HasForeignKey("CreditApplicationId");
                        });

                    b.OwnsOne("Applications.Application.Domain.Application.Declaration", "Declaration", b1 =>
                        {
                            b1.Property<string>("CreditApplicationId");

                            b1.Property<decimal>("AverageNetMonthlyIncome");

                            b1.HasKey("CreditApplicationId");

                            b1.ToTable("CreditApplication");

                            b1.ToJson("Declaration");

                            b1.WithOwner()
                                .HasForeignKey("CreditApplicationId");
                        });

                    b.Navigation("CustomerPersonalData")
                        .IsRequired();

                    b.Navigation("Declaration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
