//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.805.0 using the following command:
// xscgen BPMN20.xsd -o ..\Model -s --nc
namespace Spec.DD.DC;

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.805.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Font", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Font", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
public partial class Font
{
    
    [System.Xml.Serialization.XmlAttributeAttribute("name")]
    public string Name { get; set; }
    
    [System.Xml.Serialization.XmlAttributeAttribute("size")]
    public double Size { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the Size property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeSpecified { get; set; }
    
    [System.Xml.Serialization.XmlAttributeAttribute("isBold")]
    public bool IsBold { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the IsBold property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsBoldSpecified { get; set; }
    
    [System.Xml.Serialization.XmlAttributeAttribute("isItalic")]
    public bool IsItalic { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the IsItalic property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsItalicSpecified { get; set; }
    
    [System.Xml.Serialization.XmlAttributeAttribute("isUnderline")]
    public bool IsUnderline { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the IsUnderline property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsUnderlineSpecified { get; set; }
    
    [System.Xml.Serialization.XmlAttributeAttribute("isStrikeThrough")]
    public bool IsStrikeThrough { get; set; }
    
    /// <summary>
    /// <para xml:lang="en">Gets or sets a value indicating whether the IsStrikeThrough property is specified.</para>
    /// </summary>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsStrikeThroughSpecified { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.805.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Point", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Point", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
public partial class Point
{
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute()]
    [System.Xml.Serialization.XmlAttributeAttribute("x")]
    public double X { get; set; }
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute()]
    [System.Xml.Serialization.XmlAttributeAttribute("y")]
    public double Y { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.805.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("Bounds", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("Bounds", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
public partial class Bounds
{
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute()]
    [System.Xml.Serialization.XmlAttributeAttribute("x")]
    public double X { get; set; }
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute()]
    [System.Xml.Serialization.XmlAttributeAttribute("y")]
    public double Y { get; set; }
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute()]
    [System.Xml.Serialization.XmlAttributeAttribute("width")]
    public double Width { get; set; }
    
    [System.ComponentModel.DataAnnotations.RequiredAttribute()]
    [System.Xml.Serialization.XmlAttributeAttribute("height")]
    public double Height { get; set; }
}
