conductor.db.type=postgres
conductor.queue.type=postgres
conductor.external-payload-storage.type=postgres

spring.datasource.url=${CONDUCTOR_DATABASE_JDBCCONNECTIONSTRING}
spring.datasource.username=${CONDUCTOR_DATABASE_USERNAME}
spring.datasource.password=${CONDUCTOR_DATABASE_PASSWORD}

conductor.indexing.enabled=true
conductor.indexing.type=postgres
conductor.elasticsearch.version=0
