// <auto-generated />
using Applications.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Applications.WebApi.Migrations.SqlServer
{
    [DbContext(typeof(CreditApplicationDbContextSqlServer))]
    [Migration("20260508180619_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Applications.Application.Domain.Application.CreditApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreditPeriodInMonths")
                        .HasColumnType("int");

                    b.Property<string>("States")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CreditApplication", (string)null);
                });

            modelBuilder.Entity("Applications.Application.Domain.Application.CreditApplication", b =>
                {
                    b.OwnsOne("Applications.Application.Domain.Application.CustomerPersonalData", "CustomerPersonalData", b1 =>
                        {
                            b1.Property<string>("CreditApplicationId");

                            b1.Property<string>("DocumentId")
                                .IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired();

                            b1.Property<string>("LastName")
                                .IsRequired();

                            b1.HasKey("CreditApplicationId");

                            b1.ToTable("CreditApplication");

                            b1.ToJson("CustomerPersonalData");

                            b1.WithOwner()
                                .HasForeignKey("CreditApplicationId");
                        });

                    b.OwnsOne("Applications.Application.Domain.Application.Declaration", "Declaration", b1 =>
                        {
                            b1.Property<string>("CreditApplicationId");

                            b1.Property<decimal>("AverageNetMonthlyIncome");

                            b1.HasKey("CreditApplicationId");

                            b1.ToTable("CreditApplication");

                            b1.ToJson("Declaration");

                            b1.WithOwner()
                                .HasForeignKey("CreditApplicationId");
                        });

                    b.Navigation("CustomerPersonalData")
                        .IsRequired();

                    b.Navigation("Declaration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
